name: pw
description: "App Pw"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_bluetooth_serial: ^0.4.0



  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.5

  shared_preferences: ^2.5.0
  audio_streamer:
    path: audio_streamer
  flutter_sound: ^9.25.4
  path_provider: ^2.1.5
  get: ^4.7.2





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo.png"
  min_sdk_android: 21



flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/Teclado/
    - assets/images/Teclado/Principal/
    - assets/images/Teclado/Config/
    - assets/images/Botones/Espanol/
    - assets/images/Botones/Ingles/
    - assets/images/Botones/Frances/
    - assets/images/Botones/Portugues/
    - assets/images/Estados/

