name: pw
description: "App Pw"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/


